[color_schemes.doom_one.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[color_schemes.doom_one.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[color_schemes.frappe.bright]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[color_schemes.frappe.cursor]
cursor = "#f2d5cf"
text = "#303446"

[color_schemes.frappe.dim]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[color_schemes.frappe.hints.end]
background = "#a5adce"
foreground = "#303446"

[color_schemes.frappe.hints.start]
background = "#e5c890"
foreground = "#303446"

[color_schemes.frappe.normal]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[color_schemes.frappe.primary]
background = "#303446"
bright_foreground = "#c6d0f5"
dim_foreground = "#c6d0f5"
foreground = "#c6d0f5"

[color_schemes.frappe.search.bar]
background = "#a5adce"
foreground = "#303446"

[color_schemes.frappe.search.focused_match]
background = "#a6d189"
foreground = "#303446"

[color_schemes.frappe.search.matches]
background = "#a5adce"
foreground = "#303446"

[color_schemes.frappe.selection]
background = "#f2d5cf"
text = "#303446"

[color_schemes.frappe.vi_mode_cursor]
cursor = "#babbf1"
text = "#303446"

[color_schemes.latte.bright]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.cursor]
cursor = "#dc8a78"
text = "#eff1f5"

[color_schemes.latte.dim]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.hints.end]
background = "#6c6f85"
foreground = "#eff1f5"

[color_schemes.latte.hints.start]
background = "#df8e1d"
foreground = "#eff1f5"

[color_schemes.latte.normal]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.primary]
background = "#eff1f5"
bright_foreground = "#4c4f69"
dim_foreground = "#4c4f69"
foreground = "#4c4f69"

[color_schemes.latte.search.bar]
background = "#6c6f85"
foreground = "#eff1f5"

[color_schemes.latte.search.focused_match]
background = "#40a02b"
foreground = "#eff1f5"

[color_schemes.latte.search.matches]
background = "#6c6f85"
foreground = "#eff1f5"

[color_schemes.latte.selection]
background = "#dc8a78"
text = "#eff1f5"

[color_schemes.latte.vi_mode_cursor]
cursor = "#7287fd"
text = "#eff1f5"

[color_schemes.macchiato.bright]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[color_schemes.macchiato.cursor]
cursor = "#f4dbd6"
text = "#24273a"

[color_schemes.macchiato.dim]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[color_schemes.macchiato.hints.end]
background = "#a5adcb"
foreground = "#24273a"

[color_schemes.macchiato.hints.start]
background = "#eed49f"
foreground = "#24273a"

[color_schemes.macchiato.normal]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[color_schemes.macchiato.primary]
background = "#24273a"
bright_foreground = "#cad3f5"
dim_foreground = "#cad3f5"
foreground = "#cad3f5"

[color_schemes.macchiato.search.bar]
background = "#a5adcb"
foreground = "#24273a"

[color_schemes.macchiato.search.focused_match]
background = "#a6da95"
foreground = "#24273a"

[color_schemes.macchiato.search.matches]
background = "#a5adcb"
foreground = "#24273a"

[color_schemes.macchiato.selection]
background = "#f4dbd6"
text = "#24273a"

[color_schemes.macchiato.vi_mode_cursor]
cursor = "#b7bdf8"
text = "#24273a"

[color_schemes.mocha.bright]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[color_schemes.mocha.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[color_schemes.mocha.dim]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[color_schemes.mocha.hints.end]
background = "#a6adc8"
foreground = "#1e1e2e"

[color_schemes.mocha.hints.start]
background = "#f9e2af"
foreground = "#1e1e2e"

[color_schemes.mocha.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[color_schemes.mocha.primary]
background = "#1e1e2e"
bright_foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
foreground = "#cdd6f4"

[color_schemes.mocha.search.bar]
background = "#a6adc8"
foreground = "#1e1e2e"

[color_schemes.mocha.search.focused_match]
background = "#a6e3a1"
foreground = "#1e1e2e"

[color_schemes.mocha.search.matches]
background = "#a6adc8"
foreground = "#1e1e2e"

[color_schemes.mocha.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[color_schemes.mocha.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[color_schemes.nord.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[color_schemes.nord.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[color_schemes.nord.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[color_schemes.solarized_dark.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[color_schemes.solarized_dark.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[color_schemes.solarized_dark.primary]
background = "0x002b36"
foreground = "0x839496"

[color_schemes.solarized_light.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[color_schemes.solarized_light.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[color_schemes.solarized_light.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[color_schemes.tomorrow_night.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[color_schemes.tomorrow_night.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[color_schemes.tomorrow_night.primary]
background = "0x181818"
foreground = "0xeaeaea"
