#!/bin/sh

bspc monitor -d $(seq 1 9)

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off

POLYBAR_PATH="$HOME/.config/polybar/start.sh"
test -f $POLYBAR_PATH && $POLYBAR_PATH || \
  (command -v notify-send && notify-send "Could not start polybar")
