#!/bin/sh

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## Clipboard
# copy current directory to clipboard
alias cdc='pwd | pbcopy'
# switch to directory from clipboard
alias cdp='cd $(pbpaste)'

## Editors
# Emacs
alias ec='emacsclient -nw'

# Vi(m) 
command -v vim &>/dev/null && alias vi='vim' 
command -v nvim &>/dev/null && alias vi='nvim'

## Tmux 
alias tml="tmux list-sessions" # list sessions
alias tma="tmux -2 attach -t $1" # attach session
alias tmk="tmux kill-session -t $1" # kill session

alias sl='sl -e'
