#!/bin/sh

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# cd
alias ..='cd ../'

## Clipboard
# copy current directory to clipboard
alias cdc='pwd | pbcopy'
# switch to directory from clipboard
alias cdp='cd $(pbpaste)'

## Editors
# Emacs
alias ec='emacsclient -nw'

# Vi(m) 
command -v vim &>/dev/null && alias vi='vim' 
command -v nvim &>/dev/null && alias vi='nvim'

## Tmux 
alias tml="tmux list-sessions" # list sessions
alias tma="tmux -2 attach -t $1" # attach session
alias tmk="tmux kill-session -t $1" # kill session

alias sl='sl -e'

alias du-gui='ncdu'

## utility functions

# adapted from https://news.ycombinator.com/item?id=32106126
fcd() {
    local dir;
    while true; do
        # exit with ^D
        dir="$(ls -a1p | grep '/$' | grep -v '^./$' | fzf --height 40% --reverse --no-multi --preview 'pwd' --preview-window=up,1,border-none --no-info)"
        test -z "${dir}" && break || cd "${dir}"
    done
}
