#!/bin/sh

# General variables
export LC_ALL=en_US.UTF-8
export LANG="$LC_ALL"
export VISUAL="vim"
export TERMINAL="alacritty"
export EDITOR="emacsclient -nw"
export READER="zathura"

# Setup PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:$HOME/.local/bin:$HOME/.dotfiles/bin

[ -d ${HOME}/.emacs.d/bin ] && export PATH=$PATH:$HOME/.emacs.d/bin


