#!/bin/sh

# General variables
export LC_ALL=en_US.UTF-8
export LC_TIME="de_DE.UTF-8"
export LANG="$LC_ALL"
export VISUAL="vim"
export TERMINAL="alacritty"
export EDITOR="emacsclient -nw"
export READER="zathura"

# Setup PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:$HOME/.local/bin:$HOME/.dotfiles/bin

# Add emacs bin to path
[ -d ${HOME}/.emacs.d/bin ] && export PATH=$PATH:$HOME/.emacs.d/bin

### PACKAGE & VERSION MANAGERS ###
# Use asdf if installed
[ -d "/opt/asdf-vm" ] && export ASDF_DATA_DIR="/opt/asdf-vm" || export ASDF_DATA_DIR="$HOME/.asdf"
[ -f "$ASDF_DATA_DIR/asdf.sh" ] && source "$ASDF_DATA_DIR/asdf.sh" # || echo "asdf not found"
# Use guix if installed
command -v guix 1>/dev/null && export GUIX_PROFILE="${HOME}/.guix-profile" && . "$GUIX_PROFILE/etc/profile" 
# load nix if installed
test -e $HOME/.nix-profile/etc/profile.d/nix.sh && source $HOME/.nix-profile/etc/profile.d/nix.sh 
# load flatpak export if flatpak is installed
command -v flatpak 1>/dev/null && export PATH="$PATH:/var/lib/flatpak/exports/bin:${HOME}/.local/share/flatpak/exports/bin"

[ -f "~/.config/shell/profile.local" ] && source ~/.config/shell/profile.local
