[colors.bright]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[colors.cursor]
cursor = "#f2d5cf"
text = "#303446"

[colors.dim]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[colors.hints.end]
background = "#a5adce"
foreground = "#303446"

[colors.hints.start]
background = "#e5c890"
foreground = "#303446"

[colors.normal]
black = "#51576d"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#f4b8e4"
red = "#e78284"
white = "#b5bfe2"
yellow = "#e5c890"

[colors.primary]
background = "#303446"
bright_foreground = "#c6d0f5"
dim_foreground = "#c6d0f5"
foreground = "#c6d0f5"

[colors.search.bar]
background = "#a5adce"
foreground = "#303446"

[colors.search.focused_match]
background = "#a6d189"
foreground = "#303446"

[colors.search.matches]
background = "#a5adce"
foreground = "#303446"

[colors.selection]
background = "#f2d5cf"
text = "#303446"

[colors.vi_mode_cursor]
cursor = "#babbf1"
text = "#303446"
