#!/bin/bash

change_theme() {
  read file
  case $file in
    /*) image=$file ;; # absolute path
    *)  image="$(pwd)/$file"
  esac
  echo "Calling $(which mktheme) $image"
  [ -e $image ] && mktheme $image && notify-send "Changed theme based on wallpaper $file" || notify-send "Could change theme with $image"
}

echo "Read key $1"
case "$1" in
  w|W|b|B)   change_theme ;;
esac
